version: "3"
services:
  nginx_django:
    container_name: nginxdjangoapp
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  nginx_app:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx_app
    ports:
      - "8081:80"
    depends_on:
      - nginx_django
volumes:
  static: